### ISSUE TITLE
Yaml File Not Loading from default Folder

### ISSUE THREAD

**Issue by balaaagi** [datawrangl3r/pg2mongo#1]
Yaml Files is not being loaded from default folder.
The program is always is looking into `/etc/pg2mongo/pg2mongo.yml` if the file is not present there program gets terminated.

**Comment by datawrangl3r** [comment]
This has been involved in the current push. It doesn't have to be /etc/pg2mongo/pg2mong.yml anymore.. it can be accessed from the current working directory.
